#!/bin/bash
function zplug_install() {
    source /ush/share/zsh/scripts/zplug/init.zsh
    source ~/.config/zsh/.zshrc
    zplug install
}

function nvim_conf() {
    echo "Run in nvim command 'PackerSync'"
}

function snapper_conf() {
    snapper -c root create-config /
    echo "Edit config file of root in /etc/snapper/configs/"
}

function download_config() {
    cd /tmp && git clone https://github.com/nicourrrn/dotfiles.git
    cp /tmp/dotfiles/home/* ~/
}
