#!/bin/bash
function zplug_install() {
    source /ush/share/zsh/scripts/zplug/init.zsh
    source ~/.config/zsh/.zshrc
    zplug install
}

function download_config() {
    cd /tmp && git clone https://github.com/nicourrrn/dotfiles.git
    cp /tmp/dotfiles/home/* ~/
}
